module Mrpc
  class SubscribeRequest < ::Protobuf::Message
    attr_reader name(): ::String

    attr_writer name(): ::String?

    def initialize: (?name: ::String?) -> void

    def []: (:name) -> ::String
          | (::Symbol) -> untyped

    def []=: (:name, ::String?) -> ::String?
           | (::Symbol, untyped) -> untyped
  end

  class PluggaloidService < ::Protobuf::Rpc::Service
  end
end
